config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {registrations: "registrations" }

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'

  resources :checkouts
  resources :products
  resources :pants
  resources :shirts
  root "products#index"

  namespace :api, defaults: {format: 'json'} do
       namespace :v1 do
      devise_scope :user do
        resources :products
        post 'registrations' => 'registrations#create', :as => 'register'
        resources :sessions, :only => [:create, :destroy]
      end
      get 'tasks' => 'tasks#index', :as => 'tasks'
    end
  end

  resources :users
end

app/models/cart.rb
class Cart < ActiveRecord::Base
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	def add
		id = params[:id]

		if session[:cart] then
			cart = session[:cart]
		else
			session[:cart] = {}
			cart = session[:cart]
	end

	if cart[id] then
		cart[id] = cart[id] + 1
	else
		cart[id] = 1
	end
	redirect_to :action => :index
	end

	def clearCart
		session[:cart] = nil
		redirect_to :action => :index
	end

	def index
		if session[:cart] then
			@cart = session[:cart]
		else
			@cart = {}
		end
	end
		end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/index.html.erb
<h1>Your Cart</h1>
 <h3 class="title"><%= link_to 'Empty Your Cart', cart_clear_path %></h3>
<br><br><br>

<% total = 0 %>

<ol>
<% @cart.each do | id, quantity | %>
	<% product = Product.find_by_id(id) %>

	<li>
		<h2 class="title"><%= link_to product.Name, product %></h2>
		<p><%= number_to_currency(product.price, :unit => '$') %></p>
		<p>Quantity:	<%= quantity %></p>
	</li>
	<% total += quantity * product.price %>

	<% end %>

	<p><b><%= number_to_currency(total, :unit => '$') %></b></p>
	</ol>


<a class="success button" href="checkouts/new">
    <i class="fa fa-shopping-cart fa-lg"></i>
Check Out
</a>